[versions]
agp = "8.13.2"
kotlin = "2.2.20"
kotlinxCoroutines = "1.10.2"
ksp = "2.3.4"
junit = "4.13.2"
runner = "1.0.2"
espressoCore = "3.0.2"
activity = "1.12.2"
material3 = "1.4.0"
appcompat = "1.7.1"
hilt = "2.57.2"
coreKtx = "1.17.0"
junitVersion = "1.3.0"
espressoCoreVersion = "3.7.0"
material = "1.13.0"
icons = "1.7.8"
lifecycle = "2.10.0"
foundationLayout = "1.10.0"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
runner = { group = "com.android.support.test", name = "runner", version.ref = "runner" }
espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
icons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "icons" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-library = { id = "com.android.library", version.ref = "agp" }
